#ifndef SRC_STATE_H
#define SRC_STATE_H

typedef enum StateType {
	QUIT,
	SWITCH_PLAYER,
	CREATE_PLAYERS = 3,
	DRAW_CREATE_PLAYERS,
	ARRANGE_SHIPS,
	DRAW_ARRANGE_SHIPS,
	ATTACK_MODE,
	DRAW_ATTACK_MODE,
	SWITCH_ATTACKING_PLAYER,
	DRAW_SWITCH_ATTACKING_PLAYER,
	END_SCREEN
} StateType;

#endif // SRC_STATE_H