#ifndef SRC_STATE_H
#define SRC_STATE_H

typedef enum StateType {
	QUIT,
	CREATE_PLAYERS,
	DRAW_CREATE_PLAYERS,
	ARRANGE_SHIPS,
	DRAW_ARRANGE_SHIPS,
	ATTACK_MODE,
	DRAW_ATTACK_MODE,
	END_SCREEN,
	DRAW_END_SCREEN
} StateType;

#endif // SRC_STATE_H